version: '2'
services:

    #
    # mender-deployments
    #
    mender-deployments:
        image: mendersoftware/deployments:1.5.0
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo

    #
    # mender-gui
    #
    mender-gui:
        image: mendersoftware/gui:1.6.0
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        environment:
            - INTEGRATION_VERSION

    #
    # mender-api-gateway
    #
    mender-api-gateway:
        image: mendersoftware/api-gateway:1.5.0
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        # critical - otherwise nginx may not detect
        # these servers and exits with 'upstream server not found'
        depends_on:
            - mender-device-auth
            - mender-device-adm
            - mender-deployments
            - mender-gui
            - mender-useradm
            - mender-inventory

    #
    # mender-device-auth
    #
    mender-device-auth:
        image: mendersoftware/deviceauth:1.6.0
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo

    #
    # mender-device-adm
    #
    mender-device-adm:
        image: mendersoftware/deviceadm:1.4.1-build4
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo

    #
    # mender-inventory
    #
    mender-inventory:
        image: mendersoftware/inventory:1.4.1
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo

    #
    # mender-useradm
    #
    mender-useradm:
        image: mendersoftware/useradm:1.6.0
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender
        depends_on:
            - mender-mongo

    mender-mongo:
        image: mongo:3.4
        extends:
            file: common.yml
            service: mender-base
        networks:
            mender:
                aliases:
                    - mongo-deployments
                    - mongo-device-adm
                    - mongo-device-auth
                    - mongo-inventory
                    - mongo-useradm

    mender-conductor:
        image: mendersoftware/mender-conductor:1.1.0
        depends_on:
            - mender-elasticsearch
            - mender-redis
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender

    mender-elasticsearch:
        image: mendersoftware/elasticsearch:2.4
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender

    mender-redis:
        image: redis:3.2.11-alpine
        extends:
            file: common.yml
            service: mender-base
        networks:
            - mender

networks:
    mender:
