version: '2'
services:

    #
    # mender-client
    #
    mender-client:
        image: mendersoftware/mender-client-qemu:1.6.1-build1
        networks:
            - mender
        stdin_open: true
        tty: true
